"""
Django settings for membresias_codigosur project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_NOCODE_DIR = os.path.dirname(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i$@e@=z3nxrz6u8jv&5u^6&5mlj_o$^7a@&(c%rz#=%5)ht_%b'

DEBUG = True
# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [c for c in os.getenv('ALLOWED_HOSTS', '').split(',') if DEBUG and c]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS=['*']

ADMINS = [('support', 'support@solvosoft.com') ]


# Application definition

INSTALLED_APPS = [

    'django.contrib.contenttypes',
    #'grappelli.dashboard',
    #'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'membership_core',
    'membership_manager',
    'membership_telbot_manager',
    'django_countries',
    'djmoney',
    'djmoney.contrib.exchange',
    'ajax_select',
    'async_notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'membresias_codigosur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'membresias_codigosur.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# databaseconf

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# enddatabaseconf

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Costa_Rica'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_NOCODE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_NOCODE_DIR, 'media/')
#LOGIN_URL = '/login'
#LOGIN_REDIRECT_URL = '/'
LOCALE_PATHS = (
    os.path.join(BASE_NOCODE_DIR, 'locale/'),
)
# python -m smtpd -c DebuggingServer -n localhost:1025
# o también ver https://github.com/mailhog/MailHog
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = os.getenv('EMAIL_PORT', '1025')
EMAIL_HOST_PASSWORD =  os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_HOST_USER =  os.getenv('EMAIL_HOST_USER', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL' ,'webmaster@localhost')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS','False').lower() == "true"
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL','False').lower() == "true"


# docker run --name membresias-redis -p 6379:6379 -d redis
CELERY_MODULE = "membresias_codigosur.celery"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_BROKER_URL = os.getenv('BROKER_URL', 'redis://localhost:6379/0')

GRAPPELLI_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'
#EXCHANGE_BACKEND = 'djmoney.contrib.exchange.backends.FixerBackend'
OPEN_EXCHANGE_RATES_APP_ID="6226bd52ee074914a7edc6e55a97c8d3"


TEST_RUNNER = 'membership_manager.tests.MyTestRunner'

ASYNC_NOTIFICATION_USER='membership_manager.Contact'
ASYNC_NOTIFICATION_USER_LOOKUP_FIELDS= {'order_by': 'first_name',
     'display': 'first_name',
     'filter': ['email__icontains',
                'first_name__icontains',
                'last_name__icontains'],
     'group_lookup': 'groups__name'}



TELEGRAM_BOT_API='926661407:AAH_pSgLYwqzSYMtspC-nU8CoY_K_kmdmCY'
TELEGRAM_BOT_WEBHOOK="https://ea4539b9.ngrok.io/telbot/"
TELEGRAM_ADMIN_GROUP_ID='-1001485781572'