"""
Django settings for membresias_codigosur project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_NOCODE_DIR = os.path.dirname(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i$@e@=z3nxrz6u8jv&5u^6&5mlj_o$^7a@&(c%rz#=%5)ht_%b'

DEBUG = True
# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [c for c in os.getenv('ALLOWED_HOSTS', '').split(',') if DEBUG and c]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS=['*']
SITE_ID = 1

ADMINS = [('support', 'sitio@solvosoft.com') ]
ASYNC_TEMPLATES_NOTIFICATION = os.path.join(BASE_NOCODE_DIR, 'news_templates/')

# Application definition

INSTALLED_APPS = [

    'django.contrib.contenttypes',
    #'grappelli.dashboard',
    #'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'membership_core',
    'membership_manager',
    'membership_telbot_manager',
    'django_countries',
    'ajax_select',
    'async_notifications',
    'markitup',
    'djgentelella',
    'mptt',
    'rest_framework',
    'chunked_upload',
    'api.apps.ApiConfig',
    'django_celery_results',
    'django_celery_beat',
    'matricula',
    'matricula.contrib.bills',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'membresias_codigosur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ASYNC_TEMPLATES_NOTIFICATION],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'membresias_codigosur.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# databaseconf

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'memb2',
        'USER': 'memb2',
        'PASSWORD': 'memb2',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# enddatabaseconf

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Set in weeks to academic app
TOKEN_CONFIRMATION_EXPIRE_DAYS = 15


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

# Set languages to academic app
LANGUAGES = (
    ('es', _('Spanish')),
    ('en', _('English')),
)

TIME_ZONE = 'America/Costa_Rica'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_NOCODE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_NOCODE_DIR, 'media/')
#LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/home/'
LOCALE_PATHS = (
    os.path.join(BASE_NOCODE_DIR, 'locale/'),
)
# python -m smtpd -c DebuggingServer -n localhost:1025
# o también ver https://github.com/mailhog/MailHog
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = os.getenv('EMAIL_PORT', '1025')
EMAIL_HOST_PASSWORD =  os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_HOST_USER =  os.getenv('EMAIL_HOST_USER', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL' ,'webmaster@localhost')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS','False').lower() == "true"
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL','False').lower() == "true"


# docker run -d --rm --name membresias-rabbitmq -p 5672:5672 -d rabbitmq:3
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_MODULE = "membresias_codigosur.celery"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['json']
CELERY_BROKER_URL = os.getenv('BROKER_URL', 'amqp://guest:guest@localhost:5672')

# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

ASYNC_NOTIFICATION_USER='membership_manager.Organization'
ASYNC_NOTIFICATION_USER_LOOKUP_FIELDS= {'order_by': 'name',
     'display': 'name',
     'filter': ['email__icontains',
                'name__icontains']}


TELEGRAM_BOT_API='1051485056:AAH8trHRYe31ZpHqVoswAbaxc2oQrKFANM0'
#TELEGRAM_BOT_API='926661407:AAH_pSgLYwqzSYMtspC-nU8CoY_K_kmdmCY'
TELEGRAM_BOT_WEBHOOK="https://ee9700fa.ngrok.io/telbot/"
TELEGRAM_ADMIN_GROUP_ID='-1001485781572'
TEST_TELEGRAM = False
ASYNC_BCC  =  'membresias@codigosur.org'
#ASYNC_SEND_ONLY_EMAIL = ['membresias@codigosur.org']
ASYNC_SMTP_DEBUG=False
ASYNC_NEWSLETTER_WIDGET = 'markitup.widgets.AdminMarkItUpWidget'


DATE_INPUT_FORMATS=[
    '%d/%m/%Y', '%d/%m/%y', '%Y-%m-%d',
]

DATETIME_INPUT_FORMATS = [
    '%m/%d/%Y %H:%M %A',
    '%m/%d/%Y %H:%M %p',
    '%Y-%m-%d %H:%M %p',
    '%d/%m/%y %H:%M %p'
]

MARKITUP_FILTER = ('markdown.markdown', {'safe_mode': True})
MARKITUP_SET = 'markitup/sets/markdown/'
JQUERY_URL = None

"""
ASYNC_NEWSLETTER_SEVER_CONFIGS={
    'host': 'localhost',
    'port': '1026',
    'fail_silently': False,
    'backend': None,
    'from': 'Luisza <luisza@luisza.com>'
    #username=my_username,
    #password=my_password,
    #use_tls=my_use_tls
}
"""