version: "3"

services:
  redis:
    container_name: "redis"
    image: "redis"
    restart: always
    networks:
      - membapp

  membresias:
    build: .
    container_name: "membresias"
    image: "membresias"
    ports:
      - "8041:80"
    links:
      - "db:database"
      - "mail"
      - "redis"
    networks:
      - membapp
    environment:
      - DB_HOST=database
      - USE_SQLITE=False
      - WAIT_DB=True
      - EMAIL_HOST=mail
      - USE_MEMCACHED=True
      - DB_NAME=membresias-db
      - DB_USER=membresias-user
      - DB_PASSWORD=membresias12345
      - BROKER_URL=redis://redis:6379/0

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    container_name: "pgadmin"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@ejemplo.com
#      - PGADMIN_DEFAULT_PASSWORD=EstaEsUnaContrasenha
#    networks:
#      - membapp
#    volumes:
#      - db-backup:/backups

  mail:
    # Dummy email client for development, see ./README.md.
    image: mailhog/mailhog
    container_name: "mailhog"
    ports:
        - "8025:8025"
    networks:
      - membapp
  memcached:
    image: memcached:1.5-alpine
    container_name: "memcached"
    restart: always
    networks:
      - membapp
  db:
    image: "postgres"
    restart: always
    container_name: "postgresdb"
    environment:
      - POSTGRES_USER=membresias-user
      - POSTGRES_PASSWORD=membresias12345
      - POSTGRES_DB=membresias-db
    networks:
      - membapp
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  nginx:
 
networks:
  membapp:
    driver: bridge
