# Generated by Django 2.2.5 on 2019-09-05 01:26

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('Chash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('membership_type', models.CharField(choices=[('Personal', 'Personal'), ('Radial', 'Radial'), ('Organizacional', 'Organizacional'), ('Global', 'Global'), ('Honoraria', 'Honoraria')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('annual_cost', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('graceperiod', 'Periodo de gracia')], default='active', max_length=10)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('Chash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250)),
                ('name', models.CharField(max_length=300)),
                ('initials', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipRenew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('end_date', models.DateTimeField()),
                ('graceperiod', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Membership')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='renewal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.RenewalPeriod'),
        ),
        migrations.AddField(
            model_name='membership',
            name='services',
            field=models.ManyToManyField(to='membership_core.Service'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('expiration_date', models.DateTimeField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('inactive', 'Inactiva')], max_length=10)),
                ('pdf_invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Membership')),
                ('renewal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.MembershipRenew')),
            ],
        ),
    ]
