# Generated by Django 3.0.6 on 2020-07-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('membership_manager', '0001_initial'), ('membership_manager', '0002_auto_20191009_1900'), ('membership_manager', '0003_auto_20191010_2358'), ('membership_manager', '0004_auto_20191017_0037'), ('membership_manager', '0005_auto_20191021_0639'), ('membership_manager', '0006_activityreport_attention'), ('membership_manager', '0007_auto_20191219_1300'), ('membership_manager', '0008_auto_20191220_0904'), ('membership_manager', '0009_auto_20191220_2025'), ('membership_manager', '0010_auto_20191223_0859'), ('membership_manager', '0011_auto_20191230_1458'), ('membership_manager', '0012_auto_20200102_1530'), ('membership_manager', '0013_auto_20200108_1155'), ('membership_manager', '0014_auto_20200113_2254'), ('membership_manager', '0015_auto_20200113_2255'), ('membership_manager', '0016_auto_20200117_1229'), ('membership_manager', '0017_auto_20200121_1113'), ('membership_manager', '0018_auto_20200121_1309'), ('membership_manager', '0019_auto_20200122_1200'), ('membership_manager', '0020_auto_20200122_1627'), ('membership_manager', '0021_auto_20200123_1326'), ('membership_manager', '0022_auto_20200123_1437'), ('membership_manager', '0023_auto_20200124_2335'), ('membership_manager', '0024_auto_20200128_0849'), ('membership_manager', '0025_auto_20200131_1056'), ('membership_manager', '0026_auto_20200219_1453'), ('membership_manager', '0027_auto_20200410_1726'), ('membership_manager', '0028_auto_20200410_1728'), ('membership_manager', '0029_auto_20200414_2310'), ('membership_manager', '0030_auto_20200511_0956')]

    initial = True

    dependencies = [
        ('membership_core', '0001_initial'),
        ('membership_core', '0006_auto_20191220_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('cellphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='celular')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins'), ('MoneyGram', 'MoneyGram'), ('WesterUnion', 'WesterUnion'), ('Transferencia Bancaria Argentina', 'Transferencia Bancaria Argentina')], max_length=250, null=True, verbose_name='Método de pago')),
                ('first_name', models.CharField(max_length=250, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('currency', models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('cellphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='celular')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins'), ('MoneyGram', 'MoneyGram'), ('WesterUnion', 'WesterUnion'), ('Transferencia Bancaria Argentina', 'Transferencia Bancaria Argentina')], max_length=250, null=True, verbose_name='Método de pago')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('initials', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Contact', verbose_name='Contacto')),
                ('currency', models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda')),
                ('identification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Identificación')),
                ('identification_type', models.CharField(blank=True, choices=[('CIF', 'CIF'), ('RFC', 'RFC'), ('RUT', 'RUT'), ('NIT', 'NIT'), ('CUIT', 'CUIT'), ('RTN', 'RTN'), ('ETC', 'ETC'), ('cedula_juridica', 'Cédula Jurídica')], max_length=50, null=True, verbose_name='Tipo de identificación')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('membership_type', models.CharField(choices=[('Personal', 'Personal'), ('Radial', 'Radial'), ('Organizacional', 'Organizacional'), ('Global', 'Global'), ('Honoraria', 'Honoraria'), ('Básica', 'Básica')], max_length=50, verbose_name='Tipo de membresía')),
                ('annual_cost', models.FloatField(verbose_name='Costo')),
                ('state', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=11, verbose_name='Estado')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership_manager.Contact', verbose_name='Contato')),
                ('currency', models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Organization')),
                ('renewal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.RenewalPeriod', verbose_name='Periodo de renovación')),
                ('apply_fees', models.BooleanField(default=False, help_text='Si no se selecciona, el campo de impuestos es ignorado', verbose_name='Aplicar impuestos')),
                ('fees', models.IntegerField(blank=True, default=13, help_text='Un número de 0 a 100', null=True, verbose_name='Impuestos')),
                ('last_renew_start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ('state', 'organization'),
            },
        ),
        migrations.CreateModel(
            name='MembershipRenew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True, verbose_name='Fecha de creación')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renews', to='membership_manager.Membership', verbose_name='Membresía')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('encobro', models.BooleanField(default=False, verbose_name='En cobro')),
            ],
            options={
                'verbose_name': 'Renovación de membresía',
                'verbose_name_plural': 'Renovaciones de membresía',
            },
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='membership_manager.Organization', verbose_name='Organización')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Si se deja en 0 y se incluye atenciones la duración en horas se calcula automáticamente', verbose_name='Duración en horas')),
                ('manual_edited', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Reporte Atencion',
                'verbose_name_plural': 'Reportes de Atencion',
            },
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Hora de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Hora de fin')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attentions', to='membership_manager.ActivityReport')),
            ],
            options={
                'verbose_name': 'Atencion',
                'verbose_name_plural': 'Atenciones',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Sin descripción', max_length=250, verbose_name='Descripción')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Membership', verbose_name='Membresía')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership_core.ServiceType', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('membership',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True, verbose_name='Fecha de creación')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('amount', models.FloatField(verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('inactive', 'Inactiva')], max_length=10, verbose_name='Estado')),
                ('pdf_invoice', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Factura en PDF')),
                ('currency', models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem_inv', to='membership_manager.Membership', verbose_name='Membresía')),
                ('renewal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_m_renews', to='membership_manager.MembershipRenew', verbose_name='Periodo de renovación')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de la Factura')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins'), ('MoneyGram', 'MoneyGram'), ('WesterUnion', 'WesterUnion'), ('Transferencia Bancaria Argentina', 'Transferencia Bancaria Argentina')], max_length=250, null=True, verbose_name='Método de pago')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago')),
                ('transaction_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Número de transaccción')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
