# Generated by Django 2.2.5 on 2019-10-10 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AlterModelOptions(
            name='membershiprenew',
            options={'verbose_name': 'Renovación de membresía', 'verbose_name_plural': 'Renovaciones de membresía'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='membershiprenew',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(max_length=200, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='payment_method',
            field=models.CharField(choices=[('Chash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(max_length=200, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Membership', verbose_name='Membresía'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Factura en PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='renewal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.MembershipRenew', verbose_name='Periodo de renovación'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('inactive', 'Inactiva')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='annual_cost',
            field=models.FloatField(verbose_name='Costo Anual'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Contact', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Radial', 'Radial'), ('Organizacional', 'Organizacional'), ('Global', 'Global'), ('Honoraria', 'Honoraria')], max_length=50, verbose_name='Tipo de membresía'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='renewal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.RenewalPeriod', verbose_name='Periodo de renovación'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='services',
            field=models.ManyToManyField(to='membership_core.Service', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('graceperiod', 'Periodo de gracia')], default='active', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='graceperiod',
            field=models.BooleanField(default=False, verbose_name='Periodo de gracia'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Membership', verbose_name='Membresía'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cellphone',
            field=models.CharField(max_length=200, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Contact', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initials',
            field=models.CharField(max_length=50, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_method',
            field=models.CharField(choices=[('Chash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.CharField(max_length=200, verbose_name='Provincia'),
        ),
    ]
