# Generated by Django 3.0.3 on 2020-05-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0001_squashed_0030_auto_20200511_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprenew',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='creation_date',
            field=models.DateField(auto_created=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='expiration_date',
            field=models.DateField(verbose_name='Fecha de expiración'),
        ),
    ]
