# Generated by Django 3.1.1 on 2020-09-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0003_Country_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership_core.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership_core.country', verbose_name='País'),
        ),
    ]
