# Generated by Django 3.1.1 on 2020-09-18 18:01

from django.db import migrations

def change_countries(apps, schema_editor):
    Country = apps.get_model('membership_core', 'Country')
    countries = {c.code: c.pk for c in Country.objects.all()}

    con = schema_editor.connection
    with con.cursor() as cursor:
        for code, pk in countries.items():
            cursor.execute("update membership_manager_contact set country=%s where country=%s",
                           [str(pk), code])
            cursor.execute("update membership_manager_organization set country=%s where country=%s",
                           [str(pk), code])

class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0011_Country_fill'),
        ('membership_manager', '0002_auto_20200523_1400'),
    ]

    operations = [
        migrations.RunPython(change_countries, reverse_code=migrations.RunPython.noop),
    ]
