# Generated by Django 2.2.5 on 2019-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0002_auto_20191009_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='annual_cost',
            field=models.FloatField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
    ]
