# Generated by Django 2.2.6 on 2019-10-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0002_auto_20191009_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprenew',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renews', to='membership_manager.Membership', verbose_name='Membresía'),
        ),
    ]
