# Generated by Django 2.2.6 on 2019-10-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0003_auto_20191010_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem_inv', to='membership_manager.Membership', verbose_name='Membresía'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='renewal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_m_renews', to='membership_manager.MembershipRenew', verbose_name='Periodo de renovación'),
        ),
        migrations.AlterField(
            model_name='membershiprenew',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renews', to='membership_manager.Membership', verbose_name='Membresía'),
        ),
    ]
