# Generated by Django 3.1 on 2020-09-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0003_auto_20200918_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership_manager.contact', verbose_name='Contacto'),
        ),
    ]
