# Generated by Django 3.1.1 on 2020-10-01 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0012_title_djgentelella'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership_manager', '0004_auto_20200924_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Nombre')),
                ('report_type', models.CharField(max_length=200, verbose_name='Tipo de reporte')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicial')),
                ('grafic', models.CharField(max_length=50, verbose_name='Tipo de gráfico')),
                ('extra_form', models.JSONField(blank=True, null=True)),
                ('info_filters', models.JSONField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('numerical', 'Numérico'), ('percentaje', 'Porcentual')], default=('numerical', 'Numérico'), max_length=50, verbose_name='Tipo de dato')),
                ('cache_table', models.TextField(blank=True, null=True)),
                ('cache_grafic', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.reporttype', verbose_name='Categoría')),
                ('country', models.ManyToManyField(blank=True, to='membership_core.Country', verbose_name='País')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
