# Generated by Django 2.2.5 on 2019-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0004_auto_20191017_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('graceperiod', 'Periodo de gracia')], default='active', max_length=11, verbose_name='Estado'),
        ),
    ]
