# Generated by Django 3.1.1 on 2020-10-05 16:32

from django.db import migrations, models


def move_contact_list_organization(apps, schema_editor):
    Organization = apps.get_model('membership_manager', 'Organization')

    for orga in Organization.objects.filter(contact__isnull=False):

        Organization.objects.create(
            name=f"{orga.contact.first_name} {orga.contact.last_name}",
            email=orga.contact.email,
            cellphone=orga.contact.cellphone,
            phone=orga.contact.phone,
            address=orga.contact.address,
            country=orga.contact.country,
            city=orga.contact.city,
            province=orga.contact.province,
            postal_code=orga.contact.postal_code,
            active=orga.contact.active,
            currency=orga.contact.currency,
            payment_method=orga.contact.payment_method,
            type=True
        )
        orga.contacts.add(Organization.objects.last())
        orga.save()


def move_contact_list_membership(apps, schema_editor):
    Membership = apps.get_model('membership_manager', 'Membership')
    Organization = apps.get_model('membership_manager', 'Organization')

    for membership in Membership.objects.filter(organization__isnull=False, contact__isnull=False):

        Organization.objects.create(
            name=f"{membership.contact.first_name} {membership.contact.last_name}",
            email=membership.contact.email,
            cellphone=membership.contact.cellphone,
            phone=membership.contact.phone,
            address=membership.contact.address,
            country=membership.contact.country,
            city=membership.contact.city,
            province=membership.contact.province,
            postal_code=membership.contact.postal_code,
            active=membership.contact.active,
            currency=membership.contact.currency,
            payment_method=membership.contact.payment_method,
            type=True
        )

        membership.organization.contacts.add(Organization.objects.last())
        membership.save()


def create_contact_membership(apps, schema_editor):
    Membership = apps.get_model('membership_manager', 'Membership')
    Organization = apps.get_model('membership_manager', 'Organization')

    for membership in Membership.objects.filter(organization__isnull=True):

        Organization.objects.create(
            name=f"{membership.contact.first_name} {membership.contact.last_name}",
            email=membership.contact.email,
            cellphone=membership.contact.cellphone,
            phone=membership.contact.phone,
            address=membership.contact.address,
            country=membership.contact.country,
            city=membership.contact.city,
            province=membership.contact.province,
            postal_code=membership.contact.postal_code,
            active=membership.contact.active,
            currency=membership.contact.currency,
            payment_method=membership.contact.payment_method,
            type=True
        )

        membership.organization = Organization.objects.last()
        membership.save()

class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0005_report_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_organization_contacts_+', to='membership_manager.Organization', verbose_name='Contactos'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(move_contact_list_organization),

        migrations.RunPython(move_contact_list_membership),

        migrations.RunPython(create_contact_membership),

    ]