# Generated by Django 2.2.5 on 2019-12-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0006_activityreport_attention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreport',
            name='time_elapsed',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='duration',
        ),
        migrations.AddField(
            model_name='activityreport',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duración en horas'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='manual_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='membership_manager.Organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='end_date',
            field=models.DateTimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='start_date',
            field=models.DateTimeField(verbose_name='Hora de inicio'),
        ),
    ]
