# Generated by Django 3.1.1 on 2020-10-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0006_auto_20201005_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
