# Generated by Django 3.1.1 on 2020-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0007_auto_20201006_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='activityreport',
            name='attention_type',
            field=models.IntegerField(choices=[(0, 'Mantenimiento del sistema'), (1, 'Presencial'), (2, 'Fallo en servicio'), (3, 'Capacitación')], default=0),
        ),
    ]
