# Generated by Django 2.2.5 on 2019-12-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0007_auto_20191219_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Si se deja en 0 y se incluye atenciones la duración en horas se calcula automáticamente', verbose_name='Duración en horas'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='manual_edited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership_manager.Contact', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250, verbose_name='Método de pago'),
        ),
    ]
