# Generated by Django 2.2.5 on 2019-12-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0006_auto_20191220_2025'),
        ('membership_manager', '0008_auto_20191220_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('organization',), 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='services',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Membership', verbose_name='Membresía')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership_core.ServiceType', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('membership',),
            },
        ),
    ]
