# Generated by Django 3.1.1 on 2020-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0008_auto_20201015_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Radial', 'Radial'), ('Organizacional', 'Organizacional'), ('Global', 'Global'), ('Honoraria', 'Honoraria'), ('Básica', 'Básica'), ('Streaming.la', 'Streaming.la')], max_length=50, verbose_name='Tipo de membresía'),
        ),
    ]
