# Generated by Django 3.1.2 on 2020-10-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0014_membershiptemplate_free_membership'),
        ('membership_manager', '0009_auto_20201022_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='free_membership',
            field=models.BooleanField(default=False, verbose_name='¿Membresía gratuita sin factura?'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='renewal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.renewalperiod', verbose_name='Período de renovación'),
        ),
    ]
