# Generated by Django 2.2.6 on 2019-12-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0009_auto_20191220_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('state', 'organization'), 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
    ]
