# Generated by Django 2.2.6 on 2019-12-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0010_auto_20191223_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attention',
            options={'verbose_name': 'Atencion', 'verbose_name_plural': 'Atenciones'},
        ),
    ]
