# Generated by Django 3.1.2 on 2020-11-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0011_auto_20201103_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('state', 'organization'), 'permissions': [('can_show_dashboard', 'Can show dashboard')], 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
    ]
