# Generated by Django 2.2.6 on 2020-01-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0011_auto_20191230_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membs', to='membership_manager.Organization'),
        ),
    ]
