# Generated by Django 3.1.3 on 2021-01-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0012_auto_20201103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad'),
        ),
    ]
