# Generated by Django 3.1.2 on 2020-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0012_auto_20201103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default='13.00', help_text='Un número de 0 a 100', max_digits=6, null=True, verbose_name='Impuestos'),
        ),
    ]
