# Generated by Django 2.2.5 on 2020-01-14 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0013_auto_20200108_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
    ]
