# Generated by Django 3.1.6 on 2021-02-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0013_auto_20210104_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attention',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='renewal_period',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='renewal_period',
        ),
        migrations.RemoveField(
            model_name='membershiprenew',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='country',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='service',
            name='servicetype',
        ),
        migrations.DeleteModel(
            name='ActivityReport',
        ),
        migrations.DeleteModel(
            name='Attention',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='MembershipRenew',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
