# Generated by Django 2.2.5 on 2020-01-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0014_auto_20200113_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='membership_core.SystemCurrency', verbose_name='Moneda'),
        ),
    ]
