# Generated by Django 2.2.5 on 2020-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0015_auto_20200113_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='identification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='organization',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('RUT', 'RUT'), ('NIT', 'NIT'), ('CUIT', 'CUIT'), ('cedula_juridica', 'Cédula Jurídica')], max_length=50, null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cellphone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia'),
        ),
    ]
