# Generated by Django 2.2.5 on 2020-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0016_auto_20200117_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono'),
        ),
    ]
