# Generated by Django 2.2.5 on 2020-01-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0017_auto_20200121_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='Sin descripción', max_length=250, verbose_name='Descripción'),
        ),
    ]
