# Generated by Django 2.2.5 on 2020-01-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0018_auto_20200121_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Contact', verbose_name='Contacto'),
        ),
    ]
