# Generated by Django 2.2.5 on 2020-01-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0019_auto_20200122_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de la Factura'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250, null=True, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='initials',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins')], max_length=250, null=True, verbose_name='Método de pago'),
        ),
    ]
