# Generated by Django 2.2.5 on 2020-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0020_auto_20200122_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins'), ('MoneyGram', 'MoneyGram'), ('WesterUnion', 'WesterUnion'), ('Transferencia Bancaria Argentina', 'Transferencia Bancaria Argentina')], max_length=250, null=True, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins'), ('MoneyGram', 'MoneyGram'), ('WesterUnion', 'WesterUnion'), ('Transferencia Bancaria Argentina', 'Transferencia Bancaria Argentina')], max_length=250, null=True, verbose_name='Método de pago'),
        ),
    ]
