# Generated by Django 2.2.5 on 2020-01-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0021_auto_20200123_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Radial', 'Radial'), ('Organizacional', 'Organizacional'), ('Global', 'Global'), ('Honoraria', 'Honoraria'), ('Básica', 'Básica')], max_length=50, verbose_name='Tipo de membresía'),
        ),
    ]
