# Generated by Django 2.2.5 on 2020-01-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0022_auto_20200123_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprenew',
            name='graceperiod',
        ),
        migrations.AddField(
            model_name='membershiprenew',
            name='encobro',
            field=models.BooleanField(default=False, verbose_name='En cobro'),
        ),
    ]
