# Generated by Django 2.2.5 on 2020-01-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership_manager', '0023_auto_20200124_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=11, verbose_name='Estado'),
        ),
    ]
