# Generated by Django 2.2.5 on 2020-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0024_auto_20200128_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Paypal', 'Paypal'), ('Bitcoins', 'Bitcoins'), ('MoneyGram', 'MoneyGram'), ('WesterUnion', 'WesterUnion'), ('Transferencia Bancaria Argentina', 'Transferencia Bancaria Argentina')], max_length=250, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Número de transaccción'),
        ),
    ]
