# Generated by Django 2.2.6 on 2020-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0025_auto_20200131_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('RUT', 'RUT'), ('NIT', 'NIT'), ('CUIT', 'CUIT'), ('RTN', 'RTN'), ('ETC', 'ETC'), ('cedula_juridica', 'Cédula Jurídica')], max_length=50, null=True, verbose_name='Tipo de identificación'),
        ),
    ]
