# Generated by Django 3.0.3 on 2020-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0026_auto_20200219_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='apply_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='fees',
            field=models.IntegerField(default=13, help_text='Un número de 0 a 100', verbose_name='Impuestos'),
        ),
    ]
