# Generated by Django 3.0.3 on 2020-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0027_auto_20200410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fees',
            field=models.IntegerField(blank=True, default=13, help_text='Un número de 0 a 100', null=True, verbose_name='Impuestos'),
        ),
    ]
