# Generated by Django 3.0.3 on 2020-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0028_auto_20200410_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_renew_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='apply_fees',
            field=models.BooleanField(default=False, help_text='Si no se selecciona, el campo de impuestos es ignorado', verbose_name='Aplicar impuestos'),
        ),
    ]
