# Generated by Django 3.0.3 on 2020-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0029_auto_20200414_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('CIF', 'CIF'), ('RFC', 'RFC'), ('RUT', 'RUT'), ('NIT', 'NIT'), ('CUIT', 'CUIT'), ('RTN', 'RTN'), ('ETC', 'ETC'), ('cedula_juridica', 'Cédula Jurídica')], max_length=50, null=True, verbose_name='Tipo de identificación'),
        ),
    ]
