"""
Django settings for upo project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_NOCODE_DIR = BASE_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'iv7m3*rs0dqdk$w160!_l^q!d@l7kb(zqtdm%wvm*8757((89$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ADMINS = [('support', 'sitio@solvosoft.com') ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'membership_core',
    'ajax_select',
    'async_notifications',
    'markitup',
    'djgentelella',
    'mptt',
    'rest_framework',
    'chunked_upload',
    'api.apps.ApiConfig',
    'django_celery_results',
    'django_celery_beat',
    'matricula',
    'matricula.contrib.bills',
    'paypal.standard.ipn'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'upo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'upo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'upo',
        'USER': 'upo',
        'PASSWORD': 'upo',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Set in weeks to academic app
TOKEN_CONFIRMATION_EXPIRE_DAYS = 15

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es'
LANGUAGES = (
    ('es', _('Spanish')),
    ('en', _('English')),
)

TIME_ZONE = 'America/Costa_Rica'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_NOCODE_DIR / 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_NOCODE_DIR / 'media/'
#LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/home/'
LOCALE_PATHS = (
     BASE_NOCODE_DIR / 'locale/',
)

TINYMCE_UPLOAD_PATH = MEDIA_ROOT / 'tinymce'

# python -m smtpd -c DebuggingServer -n localhost:1025
# o también ver https://github.com/mailhog/MailHog
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = os.getenv('EMAIL_PORT', '1025')
EMAIL_HOST_PASSWORD =  os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_HOST_USER =  os.getenv('EMAIL_HOST_USER', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL' ,'webmaster@localhost')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS','False').lower() == "true"
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL','False').lower() == "true"


CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_MODULE = "upo.celery"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['json']
CELERY_BROKER_URL = os.getenv('BROKER_URL', 'amqp://guest:guest@localhost:5672')

# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}


#ASYNC_BCC  =  'membresias@codigosur.org'
#ASYNC_SEND_ONLY_EMAIL = ['membresias@codigosur.org']
ASYNC_SMTP_DEBUG=False


DATE_INPUT_FORMATS = [
    '%d/%m/%Y', '%Y-%m-%d', '%d/%m/%y'
]

DATE_FORMAT = 'd/m/Y'

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M',
    '%m/%d/%Y %H:%M',

    '%Y-%m-%d %H:%M',
    '%d/%m/%y %H:%M',
    '%Y/%m/%d %H:%M %A',
]

MARKITUP_FILTER = ('markdown.markdown', {'safe_mode': True})
MARKITUP_SET = 'markitup/sets/markdown/'
JQUERY_URL = None

PAYPAL_TEST = True
PAYPAL_RECEIVER_EMAIL = "luisza14-buyer@gmail.com"
MY_PAYPAL_HOST = "http://academica.ngrok.io"

"""
ASYNC_NEWSLETTER_SEVER_CONFIGS={
    'host': 'localhost',
    'port': '1026',
    'fail_silently': False,
    'backend': None,
    'from': 'Luisza <luisza@luisza.com>'
    #username=my_username,
    #password=my_password,
    #use_tls=my_use_tls
}
"""
PAYPAL_ERROR_EMAIL_NOFIFY = ("secretaria@universidadpopular.red",)
PROFESSOR_GROUP_NAME = "Profesores"
ADMIN_GROUP_NAME = "Administradores Académica"
HOURS_TO_PAY = 4
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'