# Generated by Django 2.2.6 on 2019-12-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('invite_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Grupo de Telegram',
                'verbose_name_plural': 'Grupos de Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_telbot_manager.TelGroup')),
            ],
            options={
                'verbose_name': 'Grupo de Telegram',
                'verbose_name_plural': 'Grupos de Telegram',
            },
        ),
    ]
