# Generated by Django 2.2.6 on 2019-12-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_telbot_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telgroup',
            name='invite_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
