# Generated by Django 2.2.6 on 2019-12-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_telbot_manager', '0002_auto_20191230_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Usuarios de Telegram', 'verbose_name_plural': 'Usuarios de Telegram'},
        ),
    ]
