# Generated by Django 2.2.6 on 2019-12-31 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_manager', '0011_auto_20191230_1458'),
        ('membership_telbot_manager', '0004_auto_20191230_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='telgroup',
            name='organization',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Organization'),
            preserve_default=False,
        ),
    ]
