# Generated by Django 2.2.6 on 2019-12-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_telbot_manager', '0005_telgroup_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telgroup',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_manager.Organization'),
        ),
    ]
