# Generated by Django 2.2.6 on 2020-01-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_telbot_manager', '0007_auto_20191231_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telusers', to='membership_telbot_manager.TelGroup'),
        ),
    ]
