# Generated by Django 2.2.6 on 2020-01-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_telbot_manager', '0008_auto_20200102_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='group',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='groups',
            field=models.ManyToManyField(to='membership_telbot_manager.TelGroup'),
        ),
    ]
