# Generated by Django 3.1.1 on 2020-10-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_telbot_manager', '0009_auto_20200103_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
