# Generated by Django 2.2.5 on 2019-09-05 01:29

from django.db import migrations

def import_data(apps, schema_editor):
    Service = apps.get_model('membership_core', 'Service')
    RenewalPeriod = apps.get_model('membership_core', 'RenewalPeriod')
    SystemCurrency =  apps.get_model('membership_core', 'SystemCurrency')
    for name in [   "Dominios",
                    "Hosting Wordpress",
                    "Hosting Moodle",
                    "Hosting Drupal",
                    "Hosting Joomla",
                    "Hosting HTML",
                    "Listas de Correo",
                    "Streaming",
                    "Nextcloud",
                    "Correo electrónico",
                    "Mumble",
                    "Estadísticas web"
                ]:
        Service.objects.create(name=name)
    # http://www2.1010data.com/documentationcenter/discover/FunctionReference/DataTypesAndFormats/currencyUnitCodes.html
    SystemCurrency.objects.create(currency="CRC")
    SystemCurrency.objects.create(currency="HNL")
    SystemCurrency.objects.create(currency="EUR")
    SystemCurrency.objects.create(currency="USD")
    SystemCurrency.objects.create(currency="ARS")
    for c in [1,2,3,6,12,24,36]:
        RenewalPeriod.objects.create(months=c)

class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_data)
    ]
