#!/bin/bash

NAME="academica"
ENVIRONMENT_PATH=/usr/local/bin/
DJANGODIR=/app/src/                               # Django project directory
SOCKFILE=unix:/app/run/gunicorn.sock #0.0.0.0:8000  # we will communicte using this unix socket
USER=academica                                          # the user to run as
GROUP=academica                                         # the group to run as
NUM_WORKERS=${GUNICORN_WORKERS:-2}                  # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=academica.settings   # which settings file should Django use
DJANGO_WSGI_MODULE=academica.wsgi           # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $ENVIRONMENT_PATH/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=$SOCKFILE \
  --log-level=info
 

