[supervisord]
nodaemon=true
user = root

[program:membresias]
command = /MEMBRESIAS/deploy/gunicorn_start
user = membresias                                                      ; User to run as
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0                                          ; Save stderr in the same log
environment=LANG=es_CR.utf8,LC_ALL=es_CR.utf8
autostart=true
autorestart=true
stopsignal=QUIT

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=5
numprocs=1
startsecs=0
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
