[supervisord]
nodaemon=true
user = root

[program:membresias]
command = /MEMBRESIAS/deploy/gunicorn_start
user = membresias                                                      ; User to run as
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0                                          ; Save stderr in the same log
environment=LANG=es_CR.utf8,LC_ALL=es_CR.utf8
autostart=true
autorestart=true
stopsignal=QUIT

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=5
numprocs=1
startsecs=0
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:celerybeat]
command=celery beat -A membresias_codigosur --schedule /MEMBRESIAS/celery/beat.db --loglevel=INFO
directory=/MEMBRESIAS/src
user=membresias
numprocs=1
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0   
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
priority=999

[program:celery]
command=celery worker -A membresias_codigosur --loglevel=INFO
directory=/MEMBRESIAS/src
user=membresias
numprocs=1
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 600
stopasgroup=true
priority=1000

[program:celerymonitor]
command=celery flower -A membresias_codigosur --port=5555 --loglevel=INFO
directory=/MEMBRESIAS/src
user=membresias
numprocs=1
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 600
stopasgroup=true
priority=1000

