[program:academica]
command = /app/deploy/gunicorn_start
user = academica                                                      ; User to run as
environment=LANG=es_CR.utf8,LC_ALL=es_CR.utf8
autostart=true
autorestart=true
stopsignal=QUIT

[program:academicabeat]
command=/app/env/bin/celery beat -A academica --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/home/membresias/academica/src
user=membresias
numprocs=1
stderr_logfile=/var/log/supervisor/beat_stderr
stdout_logfile=/var/log/supervisor/beat_stdout
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
priority=999

[program:academicaworker]
command=/app/env/bin/celery worker -A academica --loglevel=INFO
directory=/app/src
user=academica
numprocs=1
stderr_logfile=/var/log/supervisor/worker_stderr
stdout_logfile=/var/log/supervisor/worker_stdout
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 600
stopasgroup=true
priority=1000
