[program:upo]
command = /home/membresias/upo/deploy/gunicorn_start
user = membresias                                                      ; User to run as
environment=LANG=es_CR.utf8,LC_ALL=es_CR.utf8
autostart=true
autorestart=true
stopsignal=QUIT

[program:upobeat]
command=/home/membresias/upo_env/bin/celery beat -A upo --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/home/membresias/upo/src
user=membresias
numprocs=1
stderr_logfile=/var/log/supervisor/upo_beat_stderr
stdout_logfile=/var/log/supervisor/upo_beat_stdout
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
priority=999

[program:upoworker]
command=/home/membresias/upo_env/bin/celery worker -A upo --loglevel=INFO
directory=/home/membresias/upo/src
user=membresias
numprocs=1
stderr_logfile=/var/log/supervisor/upo_worker_stderr
stdout_logfile=/var/log/supervisor/upo_worker_stdout
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 600
stopasgroup=true
priority=1000
