# Generated by Django 6.0.8 on 2026-09-19 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bills', '0001_initial'),
        ('membership_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        UnaccentExtension(),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Nombre * ')),
                ('description', models.TextField(verbose_name='Descripción * ')),
                ('image', models.FileField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug * ')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre * ')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio de periodo * ')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización de periodo * ')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['finish_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre * ')),
                ('content', models.TextField(verbose_name='Contenido * ')),
                ('workload', models.IntegerField(default=20, help_text='En horas', verbose_name='Carga horaria')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.category', verbose_name='Categoría * ')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
                'permissions': [('can_add_group_course', 'Can add course to group')],
            },
        ),
        migrations.CreateModel(
            name='FakeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Fake Group',
                'verbose_name_plural': 'Fake Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.SmallIntegerField(choices=[(0, 'Internal'), (1, 'Page'), (2, 'No utilizar')], default=0, verbose_name='Type')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('require_authentication', models.BooleanField(default=False, verbose_name='Authentication is required')),
                ('order', models.SmallIntegerField(verbose_name='Menu order')),
                ('publicated', models.BooleanField(default=True, verbose_name='Publicated')),
                ('is_index', models.BooleanField(default=False, verbose_name='Index page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.menuitem', verbose_name='Page parent')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email for students')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo_profile/', verbose_name='Foto de perfil')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['user__last_name', 'active'],
                'permissions': [('change_profile', 'Can change_profile'), ('view_reports', 'Can view_reports')],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre * ')),
                ('schedule', models.CharField(max_length=300, verbose_name='Schedule')),
                ('pre_enroll_start', models.DateTimeField(verbose_name='Hora de inicio de Pre-inscripción * ')),
                ('pre_enroll_finish', models.DateTimeField(verbose_name='Hora de finalización de Pre-inscripción * ')),
                ('enroll_start', models.DateTimeField(verbose_name='Hora de inicio de matrícula * ')),
                ('enroll_finish', models.DateTimeField(verbose_name='Hora de finalización de matrícula * ')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Es pagado * ')),
                ('notified_close', models.BooleanField(default=False, verbose_name='Was nofified as closed')),
                ('notified_open', models.BooleanField(default=False, verbose_name='Was nofified as opened')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del curso * ')),
                ('maximum', models.SmallIntegerField(verbose_name='Máximo número de estudiantes * ')),
                ('is_open', models.BooleanField(default=True, verbose_name='¿Está abierto? * ')),
                ('flow', models.SmallIntegerField(choices=[(0, 'Normal flow (manual enroll activate)'), (1, 'Auto pre-enroll (automatic enroll activate)'), (2, 'Auto enroll (automatic enroll finished)')], default=0, verbose_name='Comportamiento de matrícula * ')),
                ('duration_hours', models.IntegerField(default=20, verbose_name='Duración en horas')),
                ('expedition_date', models.DateField(blank=True, null=True, verbose_name='Certificate expedition date')),
                ('featured', models.BooleanField(default=False, verbose_name='Mostrar en destacados')),
                ('featured_image', models.ImageField(blank=True, help_text='Imagen de 1200x900', null=True, upload_to='feautures/', verbose_name='Imágen destacada')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Curso * ')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Moneda * ')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.period', verbose_name='Periodo * ')),
                ('professors', models.ManyToManyField(blank=True, to='matricula.professor', verbose_name='Professors')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
                'permissions': [('can_view_pre_enroll_group', 'Can view pre-enrolled in group'), ('can_export_enrolled_group', 'Can export students group'), ('can_list_students_group', 'Can list students group'), ('can_open_group', 'Can open group'), ('can_close_group', 'Can close group'), ('can_view_pdf_enrolled_group', 'Can view enrolled to group')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuarie *')),
                ('organization', models.CharField(max_length=150, verbose_name='Organización * ')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Número de teléfono * ')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='membership_core.country')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__last_name'],
                'permissions': [('can_recovery_pass_student', 'Can recovery pass student')],
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_finished', models.BooleanField(default=False, verbose_name='Is enroll finished?')),
                ('enroll_activate', models.BooleanField(default=False, verbose_name='Is active for enroll?')),
                ('paid_excluded', models.BooleanField(default=False, verbose_name='Full scholaship')),
                ('rejected', models.BooleanField(default=False, verbose_name='Enroll rejected?')),
                ('enroll_date', models.DateTimeField(auto_now_add=True, verbose_name='Enroll date')),
                ('bill_created', models.BooleanField(default=False, verbose_name='Bill created')),
                ('course_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved'), ('uncompleted', 'Not complete the course'), ('never_attend', 'Without lessons attended')], max_length=20, null=True, verbose_name='Status')),
                ('pdf_certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate')),
                ('go_to_one_class', models.BooleanField(default=True, verbose_name='Go to classes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.group', verbose_name='Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['group'],
                'permissions': [('can_view_qualifications', 'Can view qualifications'), ('can_qualify_students', 'Can qualify students')],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField(blank=True, choices=[(50, '50'), (100, '100')], default=(100, '100'), null=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used?')),
                ('code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Discount code')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.bill', verbose_name='Bill')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.group', verbose_name='Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['group', 'student__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.group', verbose_name='Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Waiting list',
                'verbose_name_plural': 'Waiting lists',
                'ordering': ['group', 'created_at'],
            },
        ),
    ]
