# Generated by Django 6.0.8 on 2026-09-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gateway_product_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
