# Generated by Django 3.1.7 on 2021-03-04 21:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0001_initial'),
        ('matricula', '0003_importmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField(blank=True, choices=[(50, '50'), (100, '100')], default=(100, '100'), null=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used?')),
                ('code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Discount code')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.bill', verbose_name='Bill')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['course', 'student__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email for students')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['user__last_name', 'active'],
                'permissions': [('change_profile', 'Can change_profile')],
            },
        ),
        migrations.RemoveField(
            model_name='multilingualcontent',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'permissions': [('can_add_group_course', 'Can add course to group')], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ['group'], 'permissions': [('can_view_qualifications', 'Can view qualifications'), ('can_qualify_students', 'Can qualify students')], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': [('can_view_pre_enroll_group', 'Can view pre-enrolled in group'), ('can_export_enrolled_group', 'Can export students group'), ('can_list_students_group', 'Can list students group'), ('can_open_group', 'Can open group'), ('can_close_group', 'Can close group'), ('can_view_pdf_enrolled_group', 'Can view enrolled to group')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['name'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name'], 'permissions': [('can_recovery_pass_student', 'Can recovery pass student')], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='course_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='course_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='pdf_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Enroll rejected?'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Es pagado * '),
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='student',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='membership_core.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.CharField(default=1, max_length=150, verbose_name='Organización * '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Número de teléfono * '),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Descripción * '),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.category', verbose_name='Categoría * '),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(verbose_name='Contenido * '),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del curso * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Curso * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Moneda * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='enroll_finish',
            field=models.DateTimeField(verbose_name='Hora de finalización de matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='enroll_start',
            field=models.DateTimeField(verbose_name='Hora de inicio de matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='flow',
            field=models.SmallIntegerField(choices=[(0, 'Normal flow (manual enroll activate)'), (1, 'Auto pre-enroll (automatic enroll activate)'), (2, 'Auto enroll (automatic enroll finished)')], default=0, verbose_name='Comportamiento de matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='¿Está abierto? * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='maximum',
            field=models.SmallIntegerField(verbose_name='Máximo número de estudiantes * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.period', verbose_name='Periodo * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='pre_enroll_finish',
            field=models.DateTimeField(verbose_name='Hora de finalización de Pre-matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='pre_enroll_start',
            field=models.DateTimeField(verbose_name='Hora de inicio de Pre-matrícula * '),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Internal'), (1, 'Page'), (2, 'No utilizar')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(verbose_name='Slug * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='finish_date',
            field=models.DateField(verbose_name='Fecha de finalización de periodo * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio de periodo * '),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario *'),
        ),
        migrations.DeleteModel(
            name='MenuTranslations',
        ),
        migrations.DeleteModel(
            name='MultilingualContent',
        ),
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='professors',
            field=models.ManyToManyField(blank=True, to='matricula.Professor', verbose_name='Professors'),
        ),
    ]
