# Generated by Django 3.1.7 on 2021-03-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20210304_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='membership_core.country'),
        ),
    ]
