# Generated by Django 3.1 on 2020-10-12 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20201012_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 21, 11, 5, 581888, tzinfo=utc)),
        ),
    ]
