# Generated by Django 3.1.7 on 2021-03-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0003_auto_20210310_1703'),
        ('matricula', '0005_auto_20210304_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Moneda * '),
        ),
    ]
