# Generated by Django 3.1 on 2020-10-12 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_auto_20201012_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 21, 27, 33, 548628, tzinfo=utc)),
        ),
    ]
