# Generated by Django 3.1.7 on 2021-03-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('matricula', '0006_auto_20210310_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Fake Group',
                'verbose_name_plural': 'Fake Groups',
                'ordering': ['name'],
            },
        ),
    ]
