# Generated by Django 3.1.7 on 2021-03-19 21:49

from django.db import migrations
from django.conf import settings

def load_initial_groups(apps, schema_editor):
    FakeGroup = apps.get_model('matricula', 'FakeGroup')
    Group = apps.get_model('auth', 'Group')
    professor_group = Group.objects.filter(name=settings.PROFESSOR_GROUP_NAME).first()
    admin_group = Group.objects.filter(name=settings.ADMIN_GROUP_NAME).first()
    FakeGroup.objects.create(group=professor_group, name=professor_group.name)
    FakeGroup.objects.create(group=admin_group, name=admin_group.name)

class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0007_fakegroup'),
    ]

    operations = [
        migrations.RunPython(load_initial_groups),
    ]
