# Generated by Django 3.1.7 on 2021-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_load_fakegroup_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre * '),
        ),
    ]
