# Generated by Django 3.1.2 on 2020-11-04 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0010_auto_20201103_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(default=1, max_length=50, verbose_name='Url del menú'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 21, 39, 47, 51231, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MenuTranslations',
        ),
    ]
