# Generated by Django 3.1.7 on 2021-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0010_auto_20210328_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notified_close',
            field=models.BooleanField(default=False, verbose_name='Was nofified as closed'),
        ),
        migrations.AddField(
            model_name='group',
            name='notified_open',
            field=models.BooleanField(default=False, verbose_name='Was nofified as opened'),
        ),
    ]
