# Generated by Django 3.1.7 on 2021-04-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0011_auto_20210329_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
