# Generated by Django 3.1.7 on 2021-04-10 21:57
from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0012_auto_20210409_1419'),
    ]

    operations = [
        UnaccentExtension()
    ]
