# Generated by Django 3.1.2 on 2020-11-04 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0012_auto_20201104_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='default content', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 22, 19, 24, 350631, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MultilingualContent',
        ),
    ]
