# Generated by Django 3.1 on 2020-11-05 01:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_auto_20201104_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 1, 7, 37, 119412, tzinfo=utc)),
        ),
    ]
