# Generated by Django 3.1.7 on 2021-04-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_auto_20210410_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
    ]
