# Generated by Django 3.1.7 on 2021-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0014_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='paid_excluded',
            field=models.BooleanField(default=False, verbose_name='Full scholaship'),
        ),
    ]
