# Generated by Django 3.1.2 on 2020-11-05 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0014_auto_20201104_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 44, 36, 883811, tzinfo=utc)),
        ),
    ]
