# Generated by Django 3.1.2 on 2020-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0015_auto_20201105_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_add_group_course', 'Can add course to group')], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dolar'), ('EUR', 'Euro'), ('CRC', 'Colon Costa Rica')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Internal'), (1, 'Page'), (2, 'No utilizar')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
