# Generated by Django 3.1.1 on 2020-11-10 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0015_auto_20201105_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dolar'), ('EUR', 'Euro'), ('CRC', 'Colon Costa Rica')], default='CRC', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Internal'), (1, 'Page'), (2, 'No utilizar')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 19, 28, 45, 326440, tzinfo=utc)),
        ),
    ]
