# Generated by Django 3.1.3 on 2020-11-18 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_auto_20201110_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField(blank=True, choices=[(50, '50'), (100, '100')], default=(100, '100'), null=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used?')),
                ('code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Discount code')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student')),
            ],
        ),
    ]
