# Generated by Django 3.1.7 on 2021-04-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_auto_20210414_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['group', 'student__user__last_name'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='course',
        ),
        migrations.AddField(
            model_name='coupon',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.group', verbose_name='Group'),
        ),
    ]
