# Generated by Django 3.1.2 on 2020-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_auto_20201112_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Es gratuito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='flow',
            field=models.SmallIntegerField(choices=[(0, 'Normal flow (manual enroll activate)'), (1, 'Auto pre-enroll (automatic enroll activate)'), (2, 'Auto enroll (automatic enroll finished)')], default=2, verbose_name='Enrollment behavior'),
        ),
    ]
