# Generated by Django 3.1.3 on 2020-11-11 18:35

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('matricula', '0016_auto_20201110_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('personal_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Personal description')),
            ],
        ),
        migrations.AddField(
            model_name='enroll',
            name='course_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='course_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 18, 35, 56, 702448, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='group',
            name='professors',
            field=models.ManyToManyField(blank=True, to='matricula.Professor', verbose_name='Professors'),
        ),
    ]
