# Generated by Django 3.1.3 on 2020-11-13 15:02

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('matricula', '0016_auto_20201112_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, serialize=False, to='auth.user')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email for students')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ]
        ),

        migrations.AddField(
            model_name='enroll',
            name='course_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='course_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 15, 2, 6, 659907, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='group',
            name='professors',
            field=models.ManyToManyField(blank=True, to='matricula.Professor', verbose_name='Professors'),
        ),
    ]
