# Generated by Django 3.1.2 on 2020-11-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0017_auto_20201112_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_free',
        ),
        migrations.AddField(
            model_name='group',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Es pagado'),
        ),
    ]
