# Generated by Django 3.1.7 on 2021-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0018_auto_20210510_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration_hours',
            field=models.IntegerField(default=4, verbose_name='Duración en horas'),
        ),
        migrations.AddField(
            model_name='group',
            name='expedition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Certificate expedition date'),
        ),
    ]
