# Generated by Django 3.1.2 on 2020-11-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0018_auto_20201112_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('can_list_students_group', 'Can list students'), ('can_export_enrolled_group', 'Can export students group')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
