# Generated by Django 3.1.7 on 2021-05-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0019_auto_20210511_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='certificate_template',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
