# Generated by Django 3.1.2 on 2020-11-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0019_auto_20201113_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('can_view_pre_enroll_group', 'Can view pre-enrolled in group'), ('can_export_enrolled_group', 'Can export students group')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
