# Generated by Django 3.1.2 on 2020-11-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0020_auto_20201113_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('can_view_pre_enroll_group', 'Can view pre-enrolled in group'), ('can_export_enrolled_group', 'Can export students group'), ('can_open_group', 'Can open group'), ('can_close_group', 'Can close group'), ('can_view_pdf_enrolled_group', 'Can view enrolled to group')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
