# Generated by Django 3.1.7 on 2021-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0020_auto_20210512_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='duration_hours',
            field=models.IntegerField(default=20, verbose_name='Duración en horas'),
        ),
    ]
