# Generated by Django 3.1.2 on 2020-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0021_auto_20201113_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='¿Está abierto?'),
        ),
    ]
