# Generated by Django 3.1.7 on 2021-05-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0021_auto_20210513_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='course_score',
        ),
    ]
