# Generated by Django 3.1.7 on 2021-05-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0022_remove_enroll_course_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student')),
            ],
            options={
                'verbose_name': 'Waiting list',
                'verbose_name_plural': 'Waiting lists',
                'ordering': ['group', 'created_at'],
            },
        ),
    ]
