# Generated by Django 3.1.2 on 2020-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0022_auto_20201116_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.CharField(default='', max_length=150, verbose_name='Organización'),
            preserve_default=False,
        ),
    ]
