# Generated by Django 3.1.7 on 2021-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0023_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo_profile/', verbose_name='Foto de perfil'),
        ),
    ]
