# Generated by Django 3.1.1 on 2020-11-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0023_student_organization'),
        ('matricula', '0017_auto_20201117_1838'),
    ]

    operations = [
    ]
