# Generated by Django 3.1.7 on 2021-05-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0024_professor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student'),
        ),
    ]
