# Generated by Django 3.2.7 on 2021-09-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0025_auto_20210525_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['user__last_name', 'active'], 'permissions': [('change_profile', 'Can change_profile'), ('view_reports', 'Can view_reports')], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
    ]
