# Generated by Django 3.1.3 on 2020-11-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20201103_1347'),
        ('matricula', '0025_auto_20201118_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.bill', verbose_name='Bill'),
        ),
    ]
