# Generated by Django 3.2.7 on 2021-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0026_alter_professor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='go_to_one_class',
            field=models.BooleanField(default=True, verbose_name='Go to classes'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='course_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved'), ('uncomplete', 'Not complete the course')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
