# Generated by Django 3.1.3 on 2020-11-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0026_coupon_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='pdf_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate'),
        ),
    ]
