# Generated by Django 3.1.3 on 2020-11-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0027_enroll_pdf_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'permissions': [('can_view_qualifications', 'Can view qualifications'), ('can_qualify_students', 'Can qualify students')], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': [('change_profile', 'Can change_profile')], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
    ]
