# Generated by Django 3.2.7 on 2021-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0027_auto_20210903_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='course_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved'), ('uncompleted', 'Not complete the course')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
