# Generated by Django 3.1.2 on 2020-12-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0028_auto_20201125_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['course', 'student__user__last_name'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'permissions': [('can_add_group_course', 'Can add course to group')], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ['group'], 'permissions': [('can_view_qualifications', 'Can view qualifications'), ('can_qualify_students', 'Can qualify students')], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': [('can_view_pre_enroll_group', 'Can view pre-enrolled in group'), ('can_export_enrolled_group', 'Can export students group'), ('can_open_group', 'Can open group'), ('can_close_group', 'Can close group'), ('can_view_pdf_enrolled_group', 'Can view enrolled to group')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['name'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['user__last_name', 'active'], 'permissions': [('change_profile', 'Can change_profile')], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
