# Generated by Django 3.2.7 on 2021-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0028_alter_enroll_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='course_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('reproved', 'Reproved'), ('uncompleted', 'Not complete the course'), ('never_attend', 'Without lessons attended')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
