# Generated by Django 3.1.13 on 2021-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0029_alter_enroll_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='workload',
            field=models.IntegerField(default=20, help_text='En horas', verbose_name='Carga horaria'),
        ),
    ]
