# Generated by Django 3.1.13 on 2022-05-12 23:05

from django.db import migrations

def update_enrolls(apps, schema_editor):
    Enroll = apps.get_model("matricula", "Enroll")
    Enroll.objects.filter(course_status='never_attend').update(go_to_one_class=False)

class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0030_course_workload'),
    ]

    operations = [
        migrations.RunPython(update_enrolls, reverse_code=migrations.RunPython.noop )
    ]
