# Generated by Django 3.1.13 on 2022-06-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0031_updateneverattended'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Mostrar en destacados'),
        ),
    ]
