# Generated by Django 3.1.6 on 2021-02-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0015_membershiptemplate_membership_type'),
        ('matricula', '0031_auto_20201210_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='membership_core.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Número de teléfono'),
        ),
    ]
