# Generated by Django 3.1.6 on 2021-02-15 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership_core', '0015_membershiptemplate_membership_type'),
        ('matricula', '0032_auto_20210208_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': [('can_view_pre_enroll_group', 'Can view pre-enrolled in group'), ('can_export_enrolled_group', 'Can export students group'), ('can_list_students_group', 'Can list students group'), ('can_open_group', 'Can open group'), ('can_close_group', 'Can close group'), ('can_view_pdf_enrolled_group', 'Can view enrolled to group')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Descripción * '),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.category', verbose_name='Categoría * '),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(verbose_name='Contenido * '),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del curso * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Curso * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Moneda * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='enroll_finish',
            field=models.DateTimeField(verbose_name='Hora de finalización de matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='enroll_start',
            field=models.DateTimeField(verbose_name='Hora de inicio de matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='flow',
            field=models.SmallIntegerField(choices=[(0, 'Normal flow (manual enroll activate)'), (1, 'Auto pre-enroll (automatic enroll activate)'), (2, 'Auto enroll (automatic enroll finished)')], default=0, verbose_name='Comportamiento de matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='¿Está abierto? * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Es pagado * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='maximum',
            field=models.SmallIntegerField(verbose_name='Máximo número de estudiantes * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.period', verbose_name='Período * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='pre_enroll_finish',
            field=models.DateTimeField(verbose_name='Hora de finalización de Pre-matrícula * '),
        ),
        migrations.AlterField(
            model_name='group',
            name='pre_enroll_start',
            field=models.DateTimeField(verbose_name='Hora de inicio de Pre-matrícula * '),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(verbose_name='Slug * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='finish_date',
            field=models.DateField(verbose_name='Fecha de finalización de período * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio de período * '),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization',
            field=models.CharField(max_length=150, verbose_name='Organización * '),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Número de teléfono * '),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario *'),
        ),
    ]
