# Generated by Django 3.1.13 on 2022-06-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0033_group_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Imagen de 1200x900', null=True, upload_to='feautures/', verbose_name='Imágen destacada'),
        ),
    ]
