# Generated by Django 3.1.6 on 2021-02-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0033_auto_20210214_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name'], 'permissions': [('can_recovery_pass_student', 'Can recovery pass student')], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
