# Generated by Django 3.2.19 on 2023-07-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0034_auto_20220613_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['finish_date'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
    ]
