# Generated by Django 3.1.6 on 2021-02-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0034_auto_20210214_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.period', verbose_name='Periodo * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='finish_date',
            field=models.DateField(verbose_name='Fecha de finalización de periodo * '),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio de periodo * '),
        ),
    ]
