# Generated by Django 3.1.6 on 2021-02-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0035_auto_20210217_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', verbose_name='Image'),
        ),
    ]
