# Generated by Django 3.1.6 on 2021-02-19 20:53

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def update_perms_academy(apps, schema_editor):
    add_user = Permission.objects.filter(codename="add_user", content_type__app_label="auth").first()
    extra_perms = [add_user]
    enroll_group = Permission.objects.get(name="Administradores Académica")
    bill_perms = Permission.objects.filter(content_type__app_label="bills").all()

    # Apply new perms
    enroll_group.permissions.add(*bill_perms)
    enroll_group.permissions.add(*extra_perms)




class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0037_auto_20210217_1538'),
    ]

    operations = [
    ]
