# Generated by Django 3.1.6 on 2021-02-27 18:50

from django.db import migrations
from matricula.models import MenuItem
from django.core.cache import cache


def update_menu(apps, schema_editor):
    enroll = MenuItem.objects.filter(description="Matricula").first();
    if enroll:
        enroll.description = "Matrícula"
        enroll.save()

class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0038_update_permissions'),
    ]

    operations = [
        migrations.RunPython(update_menu,),
    ]
