# Generated by Django 3.1.7 on 2021-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0039_auto_20210227_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Enroll rejected?'),
        ),
    ]
