# Generated by Django 3.1.7 on 2021-03-05 03:29

from django.db import migrations
from membership_core.utils import country_data

def gen_countries(apps, schema_editor):
    Country = apps.get_model('membership_core', 'Country')
    modelcountry = []
    for country in country_data:
        modelcountry.append(Country(
            name=country_data[country],
            flag='flag-icon flag-icon-'+country.lower(),
            code=country
        ))
    Country.objects.bulk_create(modelcountry)



class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(gen_countries, reverse_code=migrations.RunPython.noop),
    ]
