# Generated by Django 3.1.7 on 2021-03-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0002_auto_20210304_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='systemcurrency',
            options={'permissions': [('can_show_dashboard', 'Puede ver el dashboard')], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterField(
            model_name='systemcurrency',
            name='rates',
            field=models.DecimalField(decimal_places=2, default=1, help_text='1 dolar equivale a X en moneda local', max_digits=10, verbose_name='Tipo de cambio'),
        ),
    ]
