# Generated by Django 2.2.5 on 2019-10-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0004_auto_20191010_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcurrency',
            name='rates',
            field=models.DecimalField(decimal_places=2, default=1, help_text='1 USD equivale a X en moneda local', max_digits=10, verbose_name='Tipo de cambio'),
        ),
    ]
