# Generated by Django 2.2.5 on 2019-12-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0005_auto_20191011_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceType',
        ),
    ]
