# Generated by Django 2.2.6 on 2020-01-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0006_auto_20191220_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_core.MembershipTemplate', verbose_name='Membresía')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership_core.ServiceType', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('membership',),
            },
        ),
    ]
