# Generated by Django 2.2.6 on 2020-01-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0007_servicemt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptemplate',
            name='services',
        ),
    ]
