# Generated by Django 3.0.3 on 2020-02-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0008_remove_membershiptemplate_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptemplate',
            name='state',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('graceperiod', 'Periodo de gracia')], default='active', max_length=15, verbose_name='Estado'),
        ),
    ]
