# Generated by Django 3.1.1 on 2020-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0009_auto_20200229_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('flag', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
