# Generated by Django 3.1.1 on 2020-09-18 17:23

from django.db import migrations
from membership_core.utils import country_data

def gen_countries(apps, schema_editor):
    Country = apps.get_model('membership_core', 'Country')
    Organization = apps.get_model('membership_manager', 'Organization')
    Contact = apps.get_model('membership_manager', 'Contact')
    countries = list(Contact.objects.all().values_list('country', flat=True))
    countries += list(Organization.objects.all().values_list('country', flat=True))
    countries = set(countries)
    modelcountry = []
    for country in countries:
        modelcountry.append(Country(
            name=country_data[country],
            flag='flag-icon flag-icon-'+country.lower(),
            code=country
        ))
    Country.objects.bulk_create(modelcountry)

class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0010_country'),
    ]

    operations = [
        migrations.RunPython(gen_countries, reverse_code=migrations.RunPython.noop),
    ]
