# Generated by Django 3.1.1 on 2020-09-18 20:29

from django.db import migrations

def cambie_nombre(apps, schema_editor):
    GentelellaSettings = apps.get_model('djgentelella', 'GentelellaSettings')
    texto = 'Sistema de Gestión de Código Sur'
    key = 'site_title'
    gst = GentelellaSettings.objects.filter(key=key).first()
    if gst:
        gst.value = texto
        gst.save()
    else:
        GentelellaSettings.objects.create(key=key, value=texto)

class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0011_Country_fill'),
        ('djgentelella', '0005_notification'),
    ]

    operations = [
        migrations.RunPython(cambie_nombre, reverse_code=migrations.RunPython.noop),

    ]
