# Generated by Django 3.1.2 on 2020-10-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0012_title_djgentelella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptemplate',
            name='renewal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_core.renewalperiod', verbose_name='Período de renovación'),
        ),
        migrations.AlterField(
            model_name='membershiptemplate',
            name='state',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('graceperiod', 'Período de gracia')], default='active', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicemt',
            name='description',
            field=models.CharField(default='Sin descripción', max_length=250, verbose_name='Descripción'),
        ),
    ]
