# Generated by Django 3.1.2 on 2020-10-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0013_auto_20201026_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptemplate',
            name='free_membership',
            field=models.BooleanField(default=False, verbose_name='¿Membresía gratuita sin factura?'),
        ),
    ]
