# Generated by Django 3.1.2 on 2020-10-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0014_membershiptemplate_free_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptemplate',
            name='membership_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Radial', 'Radial'), ('Organizacional', 'Organizacional'), ('Global', 'Global'), ('Honoraria', 'Honoraria'), ('Básica', 'Básica'), ('Streaming.la', 'Streaming.la')], default='Personal', max_length=50, verbose_name='Tipo de membresía'),
            preserve_default=False,
        ),
    ]
