# Generated by Django 3.1.6 on 2021-02-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0015_membershiptemplate_membership_type'),
    ]

    operations = [
        migrations.RunSQL('''
        drop table if exists membership_telbot_manager_telgroup cascade;
        drop table if exists membership_telbot_manager_telegramuser cascade;
        drop table if exists membership_telbot_manager_telegramnotificationtemplate cascade;
        ''')
    ]
