# Generated by Django 3.1.6 on 2021-02-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0015_membershiptemplate_membership_type'),
    ]

    operations = [
        migrations.RunSQL('''
        drop if exists table membership_telbot_manager_tel_group;
        drop if exists table membership_telbot_manager_telegram_user;
        drop if exists table membership_telbot_manager_telelegram_notification_template;
        ''')
    ]
