# Generated by Django 3.1.6 on 2021-02-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0016_auto_20210225_2223'),
    ]

    operations = [
    ]

# Generated by Django 3.1.6 on 2021-02-26 16:47

from django.db import migrations


class Migration(migrations.Migration):


    dependencies = [
        ('membership_core', '0016_auto_20210225_2223'),
    ]

    operations = [
        migrations.RunSQL('''
        drop table if exists membership_manager_activityreport cascade;
        drop table if exists membership_manager_attention cascade;
        drop table if exists membership_manager_invoice cascade;
        drop table if exists membership_manager_membership cascade;
        drop table if exists membership_manager_membershiprenew cascade;
        drop table if exists membership_manager_organization cascade;
        drop table if exists membership_manager_report cascade;
        drop table if exists membership_manager_reporttype cascade;
        drop table if exists membership_manager_servicetype cascade;
        ''')
    ]
