# Generated by Django 3.1.6 on 2021-02-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0017_auto_20210226_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemt',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='servicemt',
            name='servicetype',
        ),
        migrations.DeleteModel(
            name='MembershipTemplate',
        ),
        migrations.DeleteModel(
            name='RenewalPeriod',
        ),
        migrations.DeleteModel(
            name='ServiceMT',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
