# Generated by Django 3.1.6 on 2021-02-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0018_auto_20210226_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='systemcurrency',
            options={'permissions': [('can_show_dashboard', 'Can show dashboard')], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='systemcurrency',
            name='rates',
            field=models.DecimalField(decimal_places=2, default=1, help_text='1 USD is equal to X in local currency', max_digits=10, verbose_name='Change type'),
        ),
    ]
