# Generated by Django 3.1 on 2020-10-09 21:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.SmallIntegerField(choices=[(0, 'Internal'), (1, 'Page'), (2, 'Do not used ')], default=0, verbose_name='Type')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('require_authentication', models.BooleanField(default=False, verbose_name='Authentication is required')),
                ('order', models.SmallIntegerField(verbose_name='Menu order')),
                ('publicated', models.BooleanField(default=True, verbose_name='Publicated')),
                ('is_index', models.BooleanField(default=False, verbose_name='Index page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.menuitem', verbose_name='Page parent')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Period start date')),
                ('finish_date', models.DateField(verbose_name='Period finish date')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=3, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.page')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=3, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='Description')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('schedule', models.CharField(max_length=300, verbose_name='Schedule')),
                ('pre_enroll_start', models.DateTimeField(verbose_name='Pre enroll start hour')),
                ('pre_enroll_finish', models.DateTimeField(verbose_name='Pre enroll finish hour')),
                ('enroll_start', models.DateTimeField(verbose_name='Enroll start hour')),
                ('enroll_finish', models.DateTimeField(verbose_name='Enroll finish hour')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CRC', 'Costa Rican Colon')], default='CRC', max_length=3, verbose_name='Currency')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course cost')),
                ('maximum', models.SmallIntegerField(verbose_name='Maximum number of students')),
                ('is_open', models.BooleanField(default=True)),
                ('flow', models.SmallIntegerField(choices=[(0, 'Normal flow (manual enroll activate)'), (1, 'Auto pre-enroll (automatic enroll activate)'), (2, 'Auto enroll (automatic enroll finished)')], default=0, verbose_name='Enrollment behavior')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.period', verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_finished', models.BooleanField(default=False, verbose_name='Is enroll finished?')),
                ('enroll_activate', models.BooleanField(default=False, verbose_name='Is active for enroll?')),
                ('enroll_date', models.DateTimeField(auto_now_add=True, verbose_name='Enroll date')),
                ('bill_created', models.BooleanField(default=False, verbose_name='Bill created')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.group', verbose_name='Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
    ]
