# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-06 04:55
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.SmallIntegerField(
                choices=[(0, 'Internal'), (1, 'Page'), (2, 'Do not used ')],
                default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(
                error_messages={
                    'unique': 'A user with that username already exists.'
                },
                help_text='Required. 150 characters or fewer. Letters, digits"\
                    "and @/./+/-/_ only.',
                max_length=150, unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name='username'
            ),
        ),
    ]
