# Generated by Django 2.2 on 2020-10-07 20:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CRC', 'Costa Rican Colon')], default='CRC', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='menutranslations',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='multilingualcontent',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
