# Generated by Django 2.2 on 2020-10-08 01:48

from django.db import migrations
from matricula.menues import main_menu


def add_menu(apps, schema_editor):
    MenuItem = apps.get_model("matricula", "MenuItem")
    db_alias = schema_editor.connection.alias
    menues = []
    for menu in main_menu:
        menues.append(MenuItem(
                    name=menu[1],
                    type=0,
                    description=menu[0],
                    require_authentication=menu[2],
                    order=menu[3])
                    )
    MenuItem.objects.using(db_alias).bulk_create(menues)


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20201007_1435'),
    ]

    operations = [
        migrations.RunPython(add_menu,),
    ]
