# Generated by Django 3.1.2 on 2020-11-03 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_auto_20201103_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 18, 49, 54, 697091, tzinfo=utc)),
        ),
    ]
