# Generated by Django 3.1 on 2020-11-03 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0009_auto_20201103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 19, 46, 57, 190885, tzinfo=utc)),
        ),
    ]
