# Generated by Django 3.1 on 2020-11-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20201012_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colon_Exchange',
            new_name='ColonExchange',
        ),
    ]
