# Generated by Django 3.1.7 on 2021-03-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_core', '0001_initial'),
        ('matricula', '0003_importmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short description')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.TextField(blank=True, max_length=300, null=True)),
                ('currency', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Currency')),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.enroll', verbose_name='Enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['is_paid', 'student'],
            },
        ),
    ]
