# Generated by Django 6.0.8 on 2026-09-19 00:57

import django.db.models.deletion
import membership_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Nombre del dueño de la cuenta que realiza el deposito', max_length=50, verbose_name='Nombre del depositante')),
                ('group_name', models.CharField(help_text='Nombre del grupo a pagar', max_length=256, verbose_name='Grupo')),
                ('payment_document', models.FileField(upload_to='bank')),
                ('verified', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Pon cualquier información que nos permita emitirte la factura, información como:  Cédula/Correo electrónico/Teléfono', verbose_name='Información de factura electrónica')),
            ],
        ),
        migrations.CreateModel(
            name='SinpeMovilBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Poner el nombre del dueño del teléfono desde donde se envía el sinpe', max_length=50, verbose_name='Nombre del depositante')),
                ('group_name', models.CharField(help_text='Nombre del grupo a pagar', max_length=256, verbose_name='Grupo')),
                ('transaction_code', models.CharField(help_text='Opcional: Escriba el número de transacción que le proporciona el comprobante de SINPE', max_length=256, verbose_name='Código de trasacción')),
                ('verified', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Pon cualquier información que nos permita emitirte la factura, información como:  Cédula/Correo electrónico/Teléfono', verbose_name='Información de factura electrónica')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short description')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(default=membership_core.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['is_paid', 'student'],
            },
        ),
    ]
