# Generated by Django 6.0.8 on 2026-09-19 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.enroll', verbose_name='Enrollment'),
        ),
        migrations.AddField(
            model_name='bill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='bankbill',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
        migrations.AddField(
            model_name='sinpemovilbill',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
    ]
