# Generated by Django 6.0.8 on 2026-09-19 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(unique=True, verbose_name='Order')),
                ('checkout_url', models.URLField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In process'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20, verbose_name='Status')),
                ('status_reason', models.TextField(blank=True, default='')),
                ('authorization_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='bills.bill', verbose_name='Bill')),
            ],
            options={
                'verbose_name': 'Card payment',
                'verbose_name_plural': 'Card payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
