# Generated by Django 3.2.19 on 2023-07-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinpeMovilBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Poner el nombre del dueño del teléfono desde donde se envía el sinpe', max_length=50, verbose_name='Nombre del depositante')),
                ('group_name', models.CharField(help_text='Nombre del grupo a pagar', max_length=256, verbose_name='Grupo')),
                ('transaction_code', models.CharField(help_text='Opcional: Escriba el número de transacción que le proporciona el comprobante de SINPE', max_length=256, verbose_name='Código de trasacción')),
                ('verified', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
        migrations.CreateModel(
            name='BankBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Nombre del dueño de la cuenta que realiza el deposito', max_length=50, verbose_name='Nombre del depositante')),
                ('group_name', models.CharField(help_text='Nombre del grupo a pagar', max_length=256, verbose_name='Grupo')),
                ('payment_document', models.FileField(upload_to='bank')),
                ('verified', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
    ]
