# Generated by Django 3.1.3 on 2020-11-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0026_coupon_bill'),
        ('bills', '0003_auto_20201103_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.enroll', verbose_name='Enrollment'),
        ),
    ]
