# Generated by Django 3.2.19 on 2023-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bankbill_sinpemovilbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbill',
            name='description',
            field=models.TextField(default='', help_text='Pon cualquier información que nos permita emitirte la factura, información como:  Cédula/Correo electrónico/Teléfono', verbose_name='Información de factura electrónica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinpemovilbill',
            name='description',
            field=models.TextField(default='', help_text='Pon cualquier información que nos permita emitirte la factura, información como:  Cédula/Correo electrónico/Teléfono', verbose_name='Información de factura electrónica'),
            preserve_default=False,
        ),
    ]
