# Generated by Django 3.1.2 on 2020-12-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['is_paid', 'student'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
    ]
