# Generated by Django 3.1.2 on 2020-12-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0015_membershiptemplate_membership_type'),
        ('bills', '0005_auto_20201202_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Currency'),
        ),
    ]
