# Generated by Django 3.1.2 on 2020-12-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_core', '0015_membershiptemplate_membership_type'),
        ('bills', '0006_auto_20201210_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonexchange',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='membership_core.systemcurrency', verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
