# Generated by Django 3.1.2 on 2020-12-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_colonexchange_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColonExchange',
        ),
    ]
